server:
  port: 8082

spring:
  application:
    name: 'restaurante'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/pedido?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka